obj−m += hello−1.o
obj−m += hello−2.o
obj−m += hello−3.o
obj−m += hello−4.o
obj−m += hello−5.o
obj−m += startstop.o
startstop−objs := start.o stop.o

all:
	make −C /lib/modules//build M= modules

clean:
	make −C /lib/modules//build M= clean
